/*
 * DIO_Cfg.c
 *
 * Created: 1/17/2023 7:06:48 PM
 *  Author: Islam
 */ 
#include "DIO_Cfg.h"

extern const DIO_strPinCfg_t DIO_strPinCfg[32] =
{		
			       /*Pin Direction*//*Pull Up||Pull Down*/
		/*PIN0*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN1*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN2*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN3*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN4*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN5*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN6*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN7*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN8*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN9*/   {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN10*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN11*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN12*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN13*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN14*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN15*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN16*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN17*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN18*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN19*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN20*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN21*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN22*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN23*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN24*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN25*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN26*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN27*/  {DIO_DIR_OUTPUT,DIO_INPUT_PULL_Down},
		/*PIN28*/  {DIO_DIR_INPUT,DIO_INPUT_PULL_UP},
		/*PIN29*/  {DIO_DIR_INPUT,DIO_INPUT_PULL_UP},
		/*PIN30*/  {DIO_DIR_INPUT,DIO_INPUT_PULL_UP},
		/*PIN31*/  {DIO_DIR_INPUT,DIO_INPUT_PULL_UP}
};
