/*********************************
Timer Configuration File
*********************************/

#ifndef Timer_CFG_H
#define Timer_CFG_H

/*	
--------------Timer 0/2 Modes----------------
________#NORMAL MODE_________
	-TMR02_MODE_NORMAL
	
_________#CTC MODE_________
	-TMR02_MODE_CTC_DISCONNECTED
	-TMR02_MODE_CTC_TOGGLE
	-TMR02_MODE_CTC_CLEAR
	-TMR02_MODE_CTC_SET
	
_________#PWM MODE_________
	-TMR02_MODE_PWM_PHASE_CORRECT_DISCONNECTED
	-TMR02_MODE_PWM_PHASE_CORRECT_CLEAR
	-TMR02_MODE_PWM_PHASE_CORRECT_SET
	
________#FAST PWM MODE_________
	-TMR02_MODE_FPWM_DISCONNECTED
	-TMR02_MODE_FPWM_CLEAR
	-TMR02_MODE_FPWM_SET
*/

#define TIMER0_MODE_CFG	TMR02_MODE_NORMAL
/*
--------------Timer 0 CLK CONFIGURATIONS----------------
	-TMR02_CLK_OFF
	-TMR02_CLK_ON
	-TMR0_CLK_PRESCALER_8
	-TMR0_CLK_PRESCALER_64
	-TMR0_CLK_PRESCALER_256
	-TMR0_CLK_PRESCALER_1024
	-TMR0_XCLK_FALLING_EDGE
	-TMR0_XCLK_RISING_EDGE
*/
#define TIMER0_CLK_CFG	TMR02_CLK_ON

/*
--------------Timer 2 CLK CONFIGURATIONS----------------
	-TMR02_CLK_OFF
	-TMR02_CLK_ON
	-TMR2_CLK_PRESCALER_8
	-TMR2_CLK_PRESCALER_32
	-TMR2_CLK_PRESCALER_64
	-TMR2_CLK_PRESCALER_128
	-TMR2_CLK_PRESCALER_256
	-TMR2_CLK_PRESCALER_1024
*/
#define TIMER2_CLK_CFG	TMR02_CLK_ON
/*
	TMR0_OC_INTERRUPT_ENABLE
	TMR0_OV_INTERRUPT_ENABLE
*/
#define TIMER0_ENABLE_INTERRUPT  TMR0_OV_INTERRUPT_ENABLE

#define TIMER0_ENABLE_FOC	0

#endif /*Timer_CFG_H*/
